FROM node:latest AS deploy

RUN npm i -g \
@angular/animations@14.2.4 \
@angular/cdk@14.2.4 \
@angular/common@14.2.4 \
@angular/compiler@14.2.4 \
@angular/core@14.2.4 \
@angular/forms@14.2.4 \
@angular/material@14.2.4 \
@angular/platform-browser@14.2.4 \
@angular/platform-browser-dynamic@14.2.4 \
@angular/router@14.2.4 \
rxjs@7.5.0 \
zone.js@0.11.4 \
@angular-devkit/build-angular@14.2.4 \
@angular/cli@15.1.4 \
@angular/compiler-cli@14.2.4 \
@babel/core@7.19.3 \
@compodoc/compodoc@1.1.19 \
@koa/router@12.0.0 \
@storybook/addon-a11y@6.5.12 \
@storybook/addon-actions@6.5.12 \
@storybook/addon-essentials@6.5.12 \
@storybook/addon-interactions@6.5.12 \
@storybook/addon-links@6.5.12 \
@storybook/angular@6.5.12 \
@storybook/builder-webpack5@6.5.12 \
@storybook/jest@0.0.10 \
@storybook/manager-webpack5@6.5.12 \
@storybook/test-runner@0.8.0 \
@storybook/testing-library@0.0.13 \
@types/jasmine@3.10.0 \
@types/node@12.11.1 \
axe-playwright@1.1.11 \
babel-loader@8.2.5 \
jasmine-core@4.0.0 \
karma@6.3.0 \ 
karma-chrome-launcher@3.1.0 \
karma-coverage@2.1.0 \
karma-jasmine@4.0.0 \
karma-jasmine-html-reporter@1.7.0 \
msw@0.47.4 \
msw-storybook-addon@1.6.3 \
storybook-addon-themes@6.1.0 \
tslib@2.4.0 \
typescript@4.8.4