FROM registry.access.redhat.com/ubi7/ubi:7.9 as deploy
RUN yum install -y \
  java-1.8.0-openjdk \
  apr \
  groff-base \
  libicu \
  perl \
  perl-Carp \
  perl-Encode \
  perl-Exporter \
  perl-File-Path \
  perl-File-Temp \
  perl-Filter \
  perl-Getopt-Long \
  perl-HTTP-Tiny \
  perl-PathTools \
  perl-Pod-Escapes \
  perl-Pod-Perldoc \
  perl-Pod-Simple \
  perl-Pod-Usage \
  perl-Scalar-List-Utils \
  perl-Socket \
  perl-Storable \
  perl-Text-ParseWords \
  perl-Time-HiRes \
  perl-Time-Local \
  perl-constant \
  perl-libs \
  perl-macros \
  perl-parent \
  perl-podlators \
  perl-threads \
  perl-threads-shared \
  systemd-sysv